SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; -- NOK
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED; - NOK
--SET TRANSACTION ISOLATION LEVEL REPEATABLE READ; - OK
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE; - OK

BEGIN TRANSACTION
SELECT * FROM products WHERE Id=1
WAITFOR DELAY '00:00:10'
SELECT * FROM products WHERE Id=1
COMMIT